apiVersion: v1
kind: Service
metadata:
  name: egovframe-web-sample
  namespace: egovframe
spec:
  type: ClusterIP
  selector:
    app: egovframe-web-sample
  ports:
  - protocol: TCP
    port: 8080
    targetPort: web
